try :
    f = open('forLoops.py')
except Exception :
    print('Sorry. This file does not exist')